baseURL = 'https://bhvl-sun-power.pages.dev/'
languageCode = 'uk-UA'
title = 'A100 СЕС Запоріжжя'
 

[params]
    brandName = "A100"
    headerButtonText = "Зателефонувати"
    footerDescription = "Робимо Україну енергонезалежною та екологічно безпечною"
    copyrightText = "А100 СЕС Запоріжжя. Всі права захищені."
    phone = "12345678"


[menus]

  [[menu.main]]
    name = 'Види СЕС'
    url = '/sps/'
    identifier = "ses-types"
    weight = 10
 
  [[menu.main]]
    name = "Автономні СЕС"
    url = "/sps/autonomous-sps"
    parent = "ses-types"     
    weight = 1

  [[menu.main]]
    name = "Гібридні СЕС"
    url = "/sps/hybrid-sps/"
    parent = "ses-types"     
    weight = 2

  [[menu.main]]
    name = "Мережеві СЕС"
    url = "/sps/grid-tied-sps/"
    parent = "ses-types"     
    weight = 3

  [[menu.main]]
    name = 'СЕС під ключ'
    url = '/sps/'
    identifier = "ses-key"
    weight = 20
 
  [[menu.main]]
    name = "Для дому"
    url = "/sps/home-sps/"
    parent = "ses-key"     
    weight = 1
  
  [[menu.main]]
    name = "Для бізнесу"
    url = "/sps/business-sps/"
    parent = "ses-key"     
    weight = 2

  [[menu.main]]
    name = "Для ОСББ"
    url = "/sps/osbb-sps/"
    parent = "ses-key"     
    weight = 2
  
  [[menu.main]]
    name = "Резервне живлення"
    url = "/sps/reserve-sps/"
    parent = "ses-key"     
    weight = 4
    [menu.main.params]
        subname = "СНЕ для квартир/офісів"
        bold = true


  [[menu.main]]
    name = 'Каталог'
    url = '/products'
    identifier = "catalog"
    weight = 30

  [[menu.main]]
    name = "Готові комплекти "
    url = "/products/ready-sets/"
    parent = "catalog"     
    weight = 1
    params = { subname = "5, 10, 20, 50 кВт" }

  [[menu.main]]
    name = "Сонячні панелі"
    url = "/products/solar-panels/"
    parent = "catalog"     
    weight = 2
    params = { subname = "в т.ч. бренд А100" }

  [[menu.main]]
    name = "Інвертори"
    url = "/products/inverters/"
    parent = "catalog"     
    weight = 3

  [[menu.main]]
    name = "Акумулятори"
    url = "/products/akumulyatory/"
    parent = "catalog"     
    weight = 4

  [[menu.main]]
    name = "Комплектуючі"
    url = "/products/accessories/"
    parent = "catalog"     
    weight = 5
    params = { subname = "Кріплення, захист" }

  [[menu.main]]
    name = "Бренд А100"
    url = "/products/a100/"
    parent = "catalog"     
    weight = 6
    params = { subname = "Ексклюзив" }

  [[menu.main]]
    name = 'Послуги'
    url = '/services/'
    identifier = "services"
    weight = 40

  [[menu.main]]
    name = "Проєктування та Енергоаудит"
    url = "/services/design-and-energy-audit/"
    parent = "services"     
    weight = 1

  [[menu.main]]
    name = "Збільшення потужності"
    url = "/services/capacity-increase/"
    parent = "services"     
    weight = 2

  [[menu.main]]
    name = "Демонтаж та перенесення СЕС"
    url = "/services/relocation-of-sps/"
    parent = "services"     
    weight = 3

  [[menu.main]]
    name = "Сервіс,чистка та діагностика"
    url = "/services/service-and-cleaning"
    parent = "services"     
    weight = 4

  [[menu.main]]
    name = 'Наші роботи'
    url = '/projects'
    weight = 50


  [[menu.main]]
    name = 'Калькулятор'
    url = '/calculator'
    weight = 60

  
   [[menu.footer_nav]]
    name = "СЕС для дому"
    url = "/sps/home-sps/"    
    weight = 10
  
  [[menu.footer_nav]]
    name = "СЕС для бізнесу"
    url = "/sps/business-sps/" 
    weight = 20

   [[menu.footer_nav]]
    name = "СЕС для ОСББ"
    url = "/sps/osbb-sps/"   
    weight = 30
  
   [[menu.footer_nav]]
    name = "Резервне живлення"
    url = "/sps/reserve-sps/"
    weight = 40


 

  [[menu.footer_social]]
    name = "Наші роботи"
    url = "/projects/"
    weight = 20

  [[menu.footer_social]]
    name = "Блог"
    url = "/journal/"
    weight = 30

  [[menu.subfooter_nav]]
    name = "Політика конфіденційності"
    url = "/privacy-policy"
    weight = 10


[module]
  [module.hugoVersion]
    extended = false
    min = '0.146.0'


