media_folder: ""
public_folder: ""
content:
  - name: "legal"
    label: "Legal"
    type: "collection"
    files:
      - name: "privacy"
        label: "Privacy Policy"
        path: "content/privacy.md" # Перевір, чи є такий файл у content/
        fields:
          - { name: "title", label: "Title", type: "string" }